### ISSUE TITLE
Problems building. 

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM/sigapp-website#2]
Don't have lru-cache, which, escape-string-regexp, etc installed.

**Comment by jwlehman93** [comment]
What do you mean don't have?

**Comment by vidia** [comment]
I mean they arent dependencies. I am getting an error when I try to build it because I don't have those dependencies. I added a few manually but they kept coming so I am wondering if I am missing something.

**Comment by jwlehman93** [comment]
Ok, just wanted to verify. Did you do `npm install` at the root, then run `npm run build`?

**Comment by vidia** [comment]
I did. And I get an issue with missing dependencies. First the ones above then a bunch more. Is there a manual dependency I need before I can build this?

**Comment by vidia** [comment]
How bad would it be to have a copy of the "compiled" code directly in the repo?

**Comment by vidia** [comment]
This is a Windows problem. I'm just avoiding it.
